-- create database TestDB;
-- use TestDB;
-- create table Test (Id int primary key, Name varchar(100), BankBalance decimal);
-- insert into Test values (100, 'Theofin', 4444444);
-- select * from Test;
-- insert into Test values (102, 'Arun', 4444444);
-- insert into Test (Id, BankBalance) values (103, 444444)
-- insert into Test (Id, Name) values(104, 'Arjun');
-- update  Test set Name='Thiyophin' where Name='Thiyofin'
-- delete from test where Name is NULL or BankBalance is null
-- delete from test where id in (103,104)


-- commands to create contact management system
-- create database MyContacts;
-- use MyContacts;
-- create table Contacts (Id int identity(1,1) primary key, Name varchar(100), [Family, Workspace] varchar(100),ContactNumber varchar(12));
-- insert into Contacts values ('Thiyophin','Family',8921362009);
-- insert into Contacts values ('Arun','Family',9921362009);
-- insert into Contacts values ('Basha','Workspace',9991362009);
-- update Contacts set Name='Basha Raj' where Name='Basha';
-- select * from Contacts;
